.TH "DialogAbout" 3 "Wed Mar 8 2017" "ARSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogAbout \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialogabout\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialogAbout\fP (QWidget *parent=0)"
.br
.RI "\fIConstructeur de la classe \fBDialogAbout\fP\&. \fP"
.ti -1c
.RI "\fB~DialogAbout\fP ()"
.br
.RI "\fIDestructeur de la classe \fBDialogAbout\fP\&. \fP"
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_pushButtonQuitter_clicked\fP ()"
.br
.RI "\fIFonction qui est appelé lorsque l'on appui sur le bouton quitter\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::DialogAbout * \fBui\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DialogAbout::DialogAbout (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Constructeur de la classe \fBDialogAbout\fP\&. \fBParameters:\fP
.RS 4
\fIQWidget*\fP parent 
.RE
.PP

.SS "DialogAbout::~DialogAbout ()"

.PP
Destructeur de la classe \fBDialogAbout\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "void DialogAbout::on_pushButtonQuitter_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Fonction qui est appelé lorsque l'on appui sur le bouton quitter\&. Fermeture de la fenêtre 'about' lors de l'appui sur le bouton pour quitter\&. 
.SH "Member Data Documentation"
.PP 
.SS "Ui::DialogAbout* DialogAbout::ui\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ARSQL from the source code\&.
