.TH "main.cpp" 3 "Wed Mar 8 2017" "ARSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include 'dialogconnection\&.h'\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QSqlDatabase>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QTranslator>\fP
.br
\fC#include <QLibraryInfo>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "QSqlDatabase \fBconnection\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.SH "Variable Documentation"
.PP 
.SS "QSqlDatabase connection"

.SH "Author"
.PP 
Generated automatically by Doxygen for ARSQL from the source code\&.
